######################################################################
# $Id$
#
# (c) Copyright, Real-Time Innovations, 2016.
# All rights reserved.
# No duplications, whole or partial, manual or electronic, may be made
# without express written permission.  Any such copies, or
# revisions thereof, must display this notice unaltered.
# This code contains trade secrets of Real-Time Innovations, Inc.
#
#Modification History
#--------------------
#5.3.0,03oct16,djs created
##########################################################################

include config.mk

include $(RESOURCEHOME)/make/srcC_example.mk
